export class InstrumentoMidi {
  public nombre: string
  public archivo: string
  constructor(nombre: string, archivo: string) {
    this.nombre = nombre
    this.archivo = archivo
  }

  public static GetInstrumentos(): InstrumentoMidi[] {
    return [
      new InstrumentoMidi('Accordion', 'accordion.json'),
      new InstrumentoMidi('Bateria', 'bateria.json'),
      new InstrumentoMidi('Acoustic Bass', 'acoustic_bass.json'),
      new InstrumentoMidi('Acoustic Grand Piano', 'acoustic_grand_piano.json'),
      new InstrumentoMidi(
        'Acoustic Guitar Nylon',
        'acoustic_guitar_nylon.json',
      ),
      new InstrumentoMidi(
        'Acoustic Guitar Steel',
        'acoustic_guitar_steel.json',
      ),
      new InstrumentoMidi('Agogo', 'agogo.json'),
      new InstrumentoMidi('Alto Sax', 'alto_sax.json'),
      new InstrumentoMidi('Applause', 'applause.json'),
      new InstrumentoMidi('Bagpipe', 'bagpipe.json'),
      new InstrumentoMidi('Banjo', 'banjo.json'),
      new InstrumentoMidi('Baritone Sax', 'baritone_sax.json'),
      new InstrumentoMidi('Bassoon', 'bassoon.json'),
      new InstrumentoMidi('Bird Tweet', 'bird_tweet.json'),
      new InstrumentoMidi('Blown Bottle', 'blown_bottle.json'),
      new InstrumentoMidi('Brass Section', 'brass_section.json'),
      new InstrumentoMidi('Breath Noise', 'breath_noise.json'),
      new InstrumentoMidi(
        'Bright Acoustic Piano',
        'bright_acoustic_piano.json',
      ),
      new InstrumentoMidi('Celesta', 'celesta.json'),
      new InstrumentoMidi('Cello', 'cello.json'),
      new InstrumentoMidi('Choir Aahs', 'choir_aahs.json'),
      new InstrumentoMidi('Church Organ', 'church_organ.json'),
      new InstrumentoMidi('Clarinet', 'clarinet.json'),
      new InstrumentoMidi('Clavinet', 'clavinet.json'),
      new InstrumentoMidi('Contrabass', 'contrabass.json'),
      new InstrumentoMidi('Distortion Guitar', 'distortion_guitar.json'),
      new InstrumentoMidi('Drawbar Organ', 'drawbar_organ.json'),
      new InstrumentoMidi('Dulcimer', 'dulcimer.json'),
      new InstrumentoMidi('Electric Bass Finger', 'electric_bass_finger.json'),
      new InstrumentoMidi('Electric Bass Pick', 'electric_bass_pick.json'),
      new InstrumentoMidi('Electric Grand Piano', 'electric_grand_piano.json'),
      new InstrumentoMidi(
        'Electric Guitar Clean',
        'electric_guitar_clean.json',
      ),
      new InstrumentoMidi('Electric Guitar Jazz', 'electric_guitar_jazz.json'),
      new InstrumentoMidi(
        'Electric Guitar Muted',
        'electric_guitar_muted.json',
      ),
      new InstrumentoMidi('Electric Piano 1', 'electric_piano_1.json'),
      new InstrumentoMidi('Electric Piano 2', 'electric_piano_2.json'),
      new InstrumentoMidi('English Horn', 'english_horn.json'),
      new InstrumentoMidi('Fiddle', 'fiddle.json'),
      new InstrumentoMidi('Flute', 'flute.json'),
      new InstrumentoMidi('French Horn', 'french_horn.json'),
      new InstrumentoMidi('Fretless Bass', 'fretless_bass.json'),
      new InstrumentoMidi('Fx 1 Rain', 'fx_1_rain.json'),
      new InstrumentoMidi('Fx 2 Soundtrack', 'fx_2_soundtrack.json'),
      new InstrumentoMidi('Fx 3 Crystal', 'fx_3_crystal.json'),
      new InstrumentoMidi('Fx 4 Atmosphere', 'fx_4_atmosphere.json'),
      new InstrumentoMidi('Fx 5 Brightness', 'fx_5_brightness.json'),
      new InstrumentoMidi('Fx 6 Goblins', 'fx_6_goblins.json'),
      new InstrumentoMidi('Fx 7 Echoes', 'fx_7_echoes.json'),
      new InstrumentoMidi('Fx 8 Scifi', 'fx_8_scifi.json'),
      new InstrumentoMidi('Glockenspiel', 'glockenspiel.json'),
      new InstrumentoMidi('Guitar Fret Noise', 'guitar_fret_noise.json'),
      new InstrumentoMidi('Guitar Harmonics', 'guitar_harmonics.json'),
      new InstrumentoMidi('Gunshot', 'gunshot.json'),
      new InstrumentoMidi('Harmonica', 'harmonica.json'),
      new InstrumentoMidi('Harpsichord', 'harpsichord.json'),
      new InstrumentoMidi('Helicopter', 'helicopter.json'),
      new InstrumentoMidi('Honkytonk Piano', 'honkytonk_piano.json'),
      new InstrumentoMidi('Kalimba', 'kalimba.json'),
      new InstrumentoMidi('Koto', 'koto.json'),
      new InstrumentoMidi('Lead 1 Square', 'lead_1_square.json'),
      new InstrumentoMidi('Lead 2 Sawtooth', 'lead_2_sawtooth.json'),
      new InstrumentoMidi('Lead 3 Calliope', 'lead_3_calliope.json'),
      new InstrumentoMidi('Lead 4 Chiff', 'lead_4_chiff.json'),
      new InstrumentoMidi('Lead 5 Charang', 'lead_5_charang.json'),
      new InstrumentoMidi('Lead 6 Voice', 'lead_6_voice.json'),
      new InstrumentoMidi('Lead 7 Fifths', 'lead_7_fifths.json'),
      new InstrumentoMidi('Lead 8 Bass  Lead', 'lead_8_bass__lead.json'),
      new InstrumentoMidi('Marimba', 'marimba.json'),
      new InstrumentoMidi('Melodic Tom', 'melodic_tom.json'),
      new InstrumentoMidi('Music Box', 'music_box.json'),
      new InstrumentoMidi('Muted Trumpet', 'muted_trumpet.json'),
      new InstrumentoMidi('Oboe', 'oboe.json'),
      new InstrumentoMidi('Ocarina', 'ocarina.json'),
      new InstrumentoMidi('Orchestral Harp', 'orchestral_harp.json'),
      new InstrumentoMidi('Orchestra Hit', 'orchestra_hit.json'),
      new InstrumentoMidi('Overdriven Guitar', 'overdriven_guitar.json'),
      new InstrumentoMidi('Pad 1 New Age', 'pad_1_new_age.json'),
      new InstrumentoMidi('Pad 2 Warm', 'pad_2_warm.json'),
    ]
  }
}
